### ISSUE TITLE
Change/customize position of buttons and indicator

### ISSUE THREAD

**Issue by rekire** [eyoeldefare/onboarding#10]
I'm evaluating this component for my own app. I have a couple of issues and I'm not sure if those points are possible.
At first the text length of the sample is fine. However when I localize the text from skip to "Überspringen" the German translation the text is too long and will be displayed in two lines. IMHO the Buttons are a bit too small, but that is a different topic.

Can I put the indicator above the buttons? I see there no way, is that true?

There is also no support for a "gatekeeper" page like that you cannot skip or scroll to the next onboarding step without accepting the ToS or similar juristic requirements. In the context it would be great to get the option to change the button text per page in a easy way.

Last question: How can I customize the colors of the screen? I'm no expert in Flutter so this might be a stupid question, a small sample would be great too.

**Comment by rekire** [comment]
I looked yesterday a bit deeper in the code. It seems that this kind of customization is currently not possible and require a fork or a bigger API change (likely without a breaking change).
The position of the buttons is currently hardcoded with 4 fixed configurations. It should be possible to add a fifth way to totally customize it, but in that case the api has to be exposed.

**Comment by eyoeldefare** [comment]
The text is too long because you're using my example. The footer can be customized to look whatever you want it. It doesn't have to be a button, it can be any other widget. I am constraining the container of the button to for positioning it still. The color of the screen could be changed with the property of `background`.

**Comment by rekire** [comment]
I don't understand how I could achieve this, might be a lack of Flutter UI knowledge, can you add a small sample?

**Comment by eyoeldefare** [comment]
Well, you'll need some Flutter UI knowledge to use this plugin and I will not be showing you that.

**Comment by rekire** [comment]
Wow how generously. I'm writing my own UI based on `PageView ` which is much simpler to understand. So I don't care about your misunderstandable library.
