### ISSUE TITLE
Changing colors seems to be imposible

### ISSUE THREAD

**Issue by rekire** [eyoeldefare/onboarding#11]
I checked the code and it seems that all the colors are hardcoded in a utils class. This is not flexible at all. Please consider to change this behavior. In context of the current version 3.0.0 I do not understand why #4 was closed. This is a legit question where the answer is out of today: This is not possible right now.

**Comment by rekire** [comment]
Based on the [cookbook of Flutter](https://docs.flutter.dev/cookbook/design/themes) then you should support theming. Currently all colors are hardcoded as far I understand the code.

**Comment by eyoeldefare** [comment]
`
Theme(child:Onboarding(...),...);
`

**Comment by eyoeldefare** [comment]
Theme.of(context)

**Comment by rekire** [comment]
What exactly do you try to tell me with that?

**Comment by eyoeldefare** [comment]
I am telling you to use your own theme's style. This widget doesn't wrap the material widget.
