### ISSUE TITLE
Accessibility support

### ISSUE THREAD

**Issue by rekire** [eyoeldefare/onboarding#12]
When I start talkback on my device all pages are read at once. I would expect just the current one

**Comment by eyoeldefare** [comment]
This is because the pages are not stacked on each other but layed out horizontally out of the view of the device. So I can see why all the pages were read.

**Comment by rekire** [comment]
Are you interested in changing that wrong behavior?

**Comment by rekire** [comment]
The trick is to use `ExcludeSemantics`. Check this: https://youtu.be/bWbBgbmAdQs?t=681

**Comment by eyoeldefare** [comment]
I will see if this is a viable solution some time in the future.

**Comment by rekire** [comment]
Ah you won't do it anyway it would help other...
