### ISSUE TITLE
Expose "Skip" button text

### ISSUE THREAD

**Issue by zmeggyesi** [eyoeldefare/onboarding#2]
Please expose the text for the _Skip_ button the same way the `proceedButtonText` is exposed.

Of particular note, the current state makes one button localizable, while the other is not, which makes for subpar user experience.

**Comment by eyoeldefare** [comment]
Sorry for the late comment. I will try to do that when I have free time. It shouldn't be hard to make that dynamic.

**Comment by zmeggyesi** [comment]
Much appreciated, no matter the delay!
